# Main configuration
Messenger:
  # Allowed messaging channels to forward to other servers
  # Servers who you want to synchronize clan changes must have the same channel ID
  Channels:
    - 'survival:clansync'
    - 'sync:otherserver'

# Command configuration
Command:
  # Command name
  name: 'uclansyncbungee'
  # Command permission
  permission: 'uclansync.use'
  # Command aliases
  aliases:
    - 'usyncbungee'