# Main configuration
Messenger:
  # Messaging channel, servers who you want to synchronize clan changes
  # must have the same channel ID
  Channel: 'survival:clansync'

# Command configuration
Command:
  # Command name
  name: 'uclansyncvelocity'
  # Command permission
  permission: 'uclansync.use'
  # Command aliases
  aliases:
    - 'usyncvelocity'